---
- block:

    - name: install innoextract (!Darwin)
      package:
        name: innoextract
        state: present
      become: true
      when: ansible_os_family != "Darwin"

    - name: install innoextract (Darwin)
      homebrew:
        name: innoextract
        state: present
      become: false
      when: ansible_os_family == "Darwin"

    - name: create directories
      file:
        state: directory
        path: "{{ dosbox_gog_desktop_location }}"
        mode: "0755"

    - name: unpack installer
      command: innoextract -d {{ dosbox_root }} {{ dosbox_gog_installer_path }}
      args:
        creates: "{{ dosbox_gog_app_bin }}"

    - name: install desktop file
      template:
        src: "templates/dosbox-gog.desktop.j2"
        dest: "{{ dosbox_gog_desktop_location }}/dosbox-gog-{{ dosbox_gog_app_name_short }}.desktop"
        mode: "0644"

  tags:
    - dosbox-gog
