---
- block:

    - name: install innoextract
      package:
        name: innoextract
        state: present
      become: yes
      become_user: root

    - name: create directories
      file:
        state: directory
        path: "{{ dosbox_gog_desktop_location }}"
        mode: "0755"

    - name: unpack installer
      command: innoextract -d {{ dosbox_root }} {{ dosbox_gog_installer_path }}
      args:
        creates: "{{ dosbox_gog_app_bin }}"

    - name: install desktop file
      template:
        src: "templates/dosbox-gog.desktop.j2"
        dest: "{{ dosbox_gog_desktop_location }}/dosbox-gog-{{ dosbox_gog_app_name_short }}.desktop"
        mode: "0644"

  tags:
    - dosbox-gog
